version: "3.8"
services:
  db:
    image: postgres:12.5
    volumes:
      - ./docker_data/db:/var/lib/postgresql/data:cached
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
  app:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hello_rails:/app:cached
    environment:
      RAILS_ENV: development
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3333:3000"
    depends_on:
      - db
